parameters:
  jobName: ''             # Name of the job
  jobDisplayName: ''      # Display name of the job
  testOS: ''              # 'macOS' or 'Windows'
  pool: []
  mauiSourcePath: $(Build.SourcesDirectory)

jobs:
- job: ${{ parameters.jobName }}
  displayName: ${{ parameters.jobDisplayName }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: 120
  steps:
  - template: /eng/pipelines/arcade/setup-test-env.yml
    parameters:
      mauiSourcePath: ${{ parameters.mauiSourcePath }}

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: ${{ parameters.mauiSourcePath }}/src/Controls/tests/Core.UnitTests/Controls.Core.UnitTests.csproj
      publishTestResults: true
      testRunTitle: Controls.Core.UnitTests - ${{ parameters.testOS }}
    displayName: run Controls.Core.UnitTests - ${{ parameters.testOS }}
    continueOnError: true

  # TODO: Add remaining unit test projects

  - template: /eng/pipelines/common/fail-on-issue.yml
